<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Interní chyba serveru</title>
  <style>
    body {
      background-color: #004987;
      color: #fff;
      font-family: 'DM Sans', sans-serif;
      margin: 0;
    }

    body>div {
      height: 100vh;
      max-width: 1280px;
      margin-left: auto;
      margin-right: auto;
      font-weight: 400 !important;
      padding-left: 2rem;
      padding-right: 2rem;
      display: flex;
      align-items: center;
    }

    h1 {
      font-size: 120px;
      margin: 0;
      line-height: 1;
      font-weight: 700
    }

    h2 {
      font-size: 40px;
      font-weight: 500;
      line-height: 1;
      margin-top: 0;
      margin-bottom: 20px;
    }

    h3 {
      font-size: 20px;
      font-weight: 400;
    }
  </style>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
</head>

<body>
  <div>
    <div>
      <h1>500</h1>
      <h2>Interní chyba serveru</h2>
      <h3>Omlouváme se za potíže.</h3>
    </div>
  </div>
</body>

</html>
