<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Interní chyba serveru</title>
	<style>
		:root {
			--main-color: #eaeaea;
			--stroke-color: black;
		}

		body {
			background: var(--main-color);
		}

		h1 {
			margin: 100px auto 0 auto;
			color: var(--stroke-color);
			font-family: 'Encode Sans Semi Condensed', Verdana, sans-serif;
			font-size: 10rem;
			line-height: 10rem;
			font-weight: 200;
			text-align: center;
		}

		h2 {
			margin: 20px auto 30px auto;
			font-family: 'Encode Sans Semi Condensed', Verdana, sans-serif;
			font-size: 1.5rem;
			font-weight: 200;
			text-align: center;
		}

		h1, h2 {
			-webkit-transition: opacity 0.5s linear, margin-top 0.5s linear; /* Safari */
			transition: opacity 0.5s linear, margin-top 0.5s linear;
		}
	</style>
</head>
<body>

<h1>500</h1>
<h2>Interní chyba serveru</h2>
<h3>Omlouváme se za potíže.</h3>
</body>
</html>
